name: Deploy to cloudtype
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
          url: https://github.com/Location-based-target-authentication/BE.git
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: Location-based-target-authentication/BE
          stage: main
          yaml: |
            name: willgo
            app: java@17
            options:
              ports: "8443"
              start: ./gradlew bootRun
              env:
                - name: GOOGLE_CLIENT_ID
                  value: ${{ secrets.GOOGLE_CLIENT_ID }}
                - name: GOOGLE_CLIENT_SECRET
                  value: ${{ secrets.GOOGLE_CLIENT_SECRET }}
                - name: JWT_SECRET_KEY
                  value: ${{ secrets.JWT_SECRET_KEY }}
                - name: KAKAO_API_KEY
                  value: ${{ secrets.KAKAO_API_KEY }}
                - name: KAKAO_CLIENT_ID
                  value: ${{ secrets.KAKAO_CLIENT_ID }}
                - name: KAKAO_CLIENT_SECRET
                  value: ${{ secrets.KAKAO_CLIENT_SECRET }}
                - name: MAIL_HOST
                  value: ${{ secrets.MAIL_HOST }}
                - name: MAIL_PASSWORD
                  value: ${{ secrets.MAIL_PASSWORD }}
                - name: MAIL_PORT
                  value: ${{ secrets.MAIL_PORT }}
                - name: MAIL_USERNAME
                  value: ${{ secrets.MAIL_USERNAME }}
                - name: SERVER_IP
                  value: ${{ secrets.SERVER_IP }}
                - name: SERVER_USER
                  value: ${{ secrets.SERVER_USER }}
                - name: SSH_PRIVATE_KEY
                  value: ${{ secrets.SSH_PRIVATE_KEY }}
              buildenv: []
            context:
              git:
                url: https://github.com/Location-based-target-authentication/BE.git
                ref: main
              preset: java-springboot
